services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trackerboost-app
    depends_on:
      - postgres
      - redis
      - mongodb
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_LIFESPAN: ${JWT_TOKEN_LIFESPAN}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: spring-redis-cache
    ports:
      - "${SPRING_REDIS_PORT}:${SPRING_REDIS_PORT}"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: spring-postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27117:27117"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  redis_data:
  pg_data:
  mongodata: